-----Q1: How many total orders are recorded in the sales table?
SELECT COUNT(*) AS Total_Orders
FROM sales 


-----Q2: list all unique product categories.
SELECT DISTINCT category
FROM products

----Q3: How many customers are registered?
SELECT COUNT(*) AS Total_Customers
FROM customers

-----Q4: List all stores and the cities they are located in.
SELECT
    store_name,
    city
FROM stores

-----Q5: Products with cocoa percentage greater than 70%.
SELECT
    product_name,
    cocoa_percent
FROM products
WHERE cocoa_percent > 70

-----Q6: How many products does each brand offer?
SELECT
    brand,
    COUNT(*) AS Product_Count
FROM products
GROUP BY brand
ORDER BY Product_Count DESC

-----Q7: Find all sales where a discount was applied.
SELECT
    order_id,
    discount
FROM sales


-----Q8: Total revenue generated across all sales.
SELECT
    SUM(revenue) AS Total_Revenue
FROM sales

------Q9: Total profit made from all orders.
SELECT
    SUM(profit) AS Total_Profit
FROM sales

-----Q10: Minimum and maximum profit from a single order.
SELECT
    MIN(profit) AS Minimum_Profit,
    MAX(profit) AS Maximum_Profit
FROM sales

------Q11: Total quantity sold per product category.
SELECT
    p.category,
    SUM(s.quantity) AS Total_Quantity_Sold
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.category
ORDER BY Total_Quantity_Sold DESC

------Q12: Store name, city, and total revenue for each store.
SELECT
    st.store_name,
    st.city,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.store_name, st.city
ORDER BY Total_Revenue DESC

------Q13: Which brand generates the highest total profit?
SELECT TOP 1
    p.brand,
    SUM(s.profit) AS Total_Profit
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.brand
ORDER BY Total_Profit DESC

------Q14:Which country generates the most total revenue?
SELECT Top 1
    st.country,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.country
ORDER BY Total_Revenue DESC

-----Q15: Revenue generated by loyalty members vs non-loyalty members.
SELECT
    CASE
        WHEN c.loyalty_member = 1 THEN 'Loyalty Member'
        ELSE 'Non-Loyalty Member'
    END AS Customer_Type,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN customers c
    ON s.customer_id = c.customer_id
GROUP BY c.loyalty_member

------Q16:Top 5 products by total quantity sold.
SELECT Top 5 
    p.product_name,
    p.brand,
    SUM(s.quantity) AS Total_Quantity_Sold
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY p.product_name, p.brand
ORDER BY Total_Quantity_Sold DESC

------Q17:Which store type generates the most revenue?
SELECT
    st.store_type,
    SUM(s.revenue) AS Total_Revenue
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.store_type
ORDER BY Total_Revenue DESC

-----Q18: Average order revenue for male vs female customers.
SELECT
    c.gender,
    AVG(s.revenue) AS Average_Order_Revenue
FROM sales s
JOIN customers c
    ON s.customer_id = c.customer_id
GROUP BY c.gender

-------Q19:Which city has the highest number of orders placed?
SELECT Top 5
    st.city,
    COUNT(s.order_id) AS Total_Orders
FROM sales s
JOIN stores st
    ON s.store_id = st.store_id
GROUP BY st.city
ORDER BY Total_Orders DESC


-----Q20:Products with unit price greater than average unit price.
SELECT DISTINCT
    p.product_name,
    s.unit_price
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
WHERE s.unit_price >
(
    SELECT AVG(unit_price)
    FROM sales
)
ORDER BY s.unit_price DESC



SELECT * FROM customers;